### ISSUE TITLE
errors in readme. Configuration example

### ISSUE THREAD

**Issue by Mart-Muc** [martinbernat/homebridge-th16ermostat#5]
short:
great plugin, just found it today to switch my Sauna.

but it costed me 30 min to figure out why it doesnt switch off:

--> error in Configuration example

* "deviceCmndOff": "/cm?cmnd=power%20onf"  should be off !!!
* "pollingInterval" two times,
* Syntax error:  "," at wrong positionS

**Comment by martinbernat** [comment]
Really sorry for that, must have been my merging mistake or something.
Fixed in 1.1.2.
