### ISSUE TITLE
deltaTemp and StepTemp

### ISSUE THREAD

**Issue by Mart-Muc** [martinbernat/homebridge-th16ermostat#7]
pls catch deltaTemp == 0 or even worse: negative values
deltaTemp should be at least >= stepTemp, best multiple of deltaTemp

stepTemp is always 0.5 in my eveApp ??

**Comment by martinbernat** [comment]
Fixed in 1.1.2, added a check to avoid negative or zero values, forcing minimum value of 0.1.
There is IMO no need to have it ">= stepTemp" or multiples, we just need to prevent too frequent switching of the relay.

**Comment by Mart-Muc** [comment]
Thx, great and fast job!
